---
galaxy_info:
  author: Jorge Armando Medina
  description: Tasks for setting up jenkins service
  company: KoolOps
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  categories:
  - development
dependencies: []
