---
galaxy_info:
  author: Jorge Armando Medina
  description: Tasks for setting up local package management
  company: KoolOps
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  categories:
  - packaging
dependencies: []
